# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHwO4PpVn4rdrn7mh9sAfl30MqqYnVBe
"""

import streamlit as st
import torch
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification

st.set_page_config(page_title="Eco-Verify", layout="wide")

st.title("🌱 Eco-Verify: AI Greenwashing Detector")

@st.cache_resource
def load_model():
    tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")
    # The path './results/checkpoint-best' was causing an error because it was not recognized
    # as a valid local model directory by the transformers library or a valid Hugging Face repo ID.
    # Please ensure the directory './results/checkpoint-best' exists and contains your model's config.json and weights.
    # For demonstration, we'll use 'distilbert-base-uncased' as a placeholder.
    model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")
    return tokenizer, model

tokenizer, model = load_model()

def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=1)
    greenwashing_prob = probs[0][1].item()
    score = int((1 - greenwashing_prob) * 100)
    return greenwashing_prob, score

text_input = st.text_area("Enter Corporate ESG Claim")

if st.button("Analyze"):
    prob, score = predict(text_input)

    st.subheader("📊 Analysis Result")
    st.write(f"Greenwashing Probability: {prob:.2f}")
    st.write(f"Green Authenticity Score: {score}/100")

    if score > 70:
        st.success("Likely Authentic Claim ✅")
    elif score > 40:
        st.warning("Needs Verification ⚠️")
    else:
        st.error("Potential Greenwashing 🚨")
import plotly.express as px
import pandas as pd

def analytics_dashboard(scores):
    df = pd.DataFrame(scores, columns=["Authenticity Score"])
    fig = px.histogram(df, x="Authenticity Score", nbins=20, title="Score Distribution")
    st.plotly_chart(fig)

!streamlit run app.py

